# Generated by Django 2.2.5 on 2019-11-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'mahasiswa',
            },
        ),
    ]
