# Generated by Django 2.2.7 on 2019-11-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_mahadosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahadosen',
            name='alamat',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
