# Generated by Django 2.2.7 on 2019-11-30 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0003_mahadosen_alamat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahadosen',
            name='alamat',
        ),
    ]
